#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace classRoomWebSite.Data
{
    public partial class classRoomWebSiteDataContext : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initializes a new classRoomWebSiteDataContext object using the connection string 'classRoomWebSiteDataContext' found in the connection string section of the application configuration file.
        /// </summary>
        public classRoomWebSiteDataContext() : base("name=classRoomWebSiteDataContext", "classRoomWebSiteDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new classRoomWebSiteDataContext object.
        /// </summary>
        public classRoomWebSiteDataContext(string connectionString) : base(connectionString, "classRoomWebSiteDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new classRoomWebSiteDataContext object.
        /// </summary>
        public classRoomWebSiteDataContext(EntityConnection connection) : base(connection, "classRoomWebSiteDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        private ObjectSet<CalendarDetail> _calendarDetail;
        public ObjectSet<CalendarDetail> CalendarDetail
        {
            get
            {
                if (_calendarDetail == null)
                {
                    _calendarDetail = base.CreateObjectSet<CalendarDetail>("CalendarDetail");
                }

                return _calendarDetail;
            }
        }

        private ObjectSet<Cat1> _cat1;
        public ObjectSet<Cat1> Cat1
        {
            get
            {
                if (_cat1 == null)
                {
                    _cat1 = base.CreateObjectSet<Cat1>("Cat1");
                }

                return _cat1;
            }
        }

        private ObjectSet<Cat2> _cat2;
        public ObjectSet<Cat2> Cat2
        {
            get
            {
                if (_cat2 == null)
                {
                    _cat2 = base.CreateObjectSet<Cat2>("Cat2");
                }

                return _cat2;
            }
        }

        private ObjectSet<CourseIntro> _courseIntro;
        public ObjectSet<CourseIntro> CourseIntro
        {
            get
            {
                if (_courseIntro == null)
                {
                    _courseIntro = base.CreateObjectSet<CourseIntro>("CourseIntro");
                }

                return _courseIntro;
            }
        }

        private ObjectSet<QuestionAnser> _questionAnser;
        public ObjectSet<QuestionAnser> QuestionAnser
        {
            get
            {
                if (_questionAnser == null)
                {
                    _questionAnser = base.CreateObjectSet<QuestionAnser>("QuestionAnser");
                }

                return _questionAnser;
            }
        }

        private ObjectSet<Student> _student;
        public ObjectSet<Student> Student
        {
            get
            {
                if (_student == null)
                {
                    _student = base.CreateObjectSet<Student>("Student");
                }

                return _student;
            }
        }

        private ObjectSet<SystemUser> _systemUser;
        public ObjectSet<SystemUser> SystemUser
        {
            get
            {
                if (_systemUser == null)
                {
                    _systemUser = base.CreateObjectSet<SystemUser>("SystemUser");
                }

                return _systemUser;
            }
        }

        private ObjectSet<TaiwanZipCode> _taiwanZipCode;
        public ObjectSet<TaiwanZipCode> TaiwanZipCode
        {
            get
            {
                if (_taiwanZipCode == null)
                {
                    _taiwanZipCode = base.CreateObjectSet<TaiwanZipCode>("TaiwanZipCode");
                }

                return _taiwanZipCode;
            }
        }

        private ObjectSet<Teacher> _teacher;
        public ObjectSet<Teacher> Teacher
        {
            get
            {
                if (_teacher == null)
                {
                    _teacher = base.CreateObjectSet<Teacher>("Teacher");
                }

                return _teacher;
            }
        }
        #endregion
    }
}
#pragma warning restore 1591