#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace classRoomWebSite.Data
{
    [EdmEntityTypeAttribute(NamespaceName="classRoomWebSite.Data", Name="CalendarDetail")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class CalendarDetail : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new CalendarDetail object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        public static CalendarDetail CreateCalendarDetail(global::System.Guid identification, global::System.String subject)
        {
            CalendarDetail calendarDetail = new CalendarDetail();
            calendarDetail.Identification = identification;
            calendarDetail.Subject = subject;

            return calendarDetail;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Guid _identification;
        partial void OnIdentificationChanging(global::System.Guid value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _subject;
            }
            set
            {
                if (_subject != value)
                {
                    OnSubjectChanging(value);
                    ReportPropertyChanging("Subject");
                    _subject = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Subject");
                    OnSubjectChanged();
                }
            }
        }

        private global::System.String _subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? StartDateTime
        {
            get
            {
                return _startDateTime;
            }
            set
            {
                if (_startDateTime != value)
                {
                    OnStartDateTimeChanging(value);
                    ReportPropertyChanging("StartDateTime");
                    _startDateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StartDateTime");
                    OnStartDateTimeChanged();
                }
            }
        }

        private global::System.DateTime? _startDateTime;
        partial void OnStartDateTimeChanging(global::System.DateTime? value);
        partial void OnStartDateTimeChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? EndDateTime
        {
            get
            {
                return _endDateTime;
            }
            set
            {
                if (_endDateTime != value)
                {
                    OnEndDateTimeChanging(value);
                    ReportPropertyChanging("EndDateTime");
                    _endDateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EndDateTime");
                    OnEndDateTimeChanged();
                }
            }
        }

        private global::System.DateTime? _endDateTime;
        partial void OnEndDateTimeChanging(global::System.DateTime? value);
        partial void OnEndDateTimeChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? FeeStaff
        {
            get
            {
                return _feeStaff;
            }
            set
            {
                if (_feeStaff != value)
                {
                    OnFeeStaffChanging(value);
                    ReportPropertyChanging("FeeStaff");
                    _feeStaff = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeeStaff");
                    OnFeeStaffChanged();
                }
            }
        }

        private global::System.Int32? _feeStaff;
        partial void OnFeeStaffChanging(global::System.Int32? value);
        partial void OnFeeStaffChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? FeeNonStaff
        {
            get
            {
                return _feeNonStaff;
            }
            set
            {
                if (_feeNonStaff != value)
                {
                    OnFeeNonStaffChanging(value);
                    ReportPropertyChanging("FeeNonStaff");
                    _feeNonStaff = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeeNonStaff");
                    OnFeeNonStaffChanged();
                }
            }
        }

        private global::System.Int32? _feeNonStaff;
        partial void OnFeeNonStaffChanging(global::System.Int32? value);
        partial void OnFeeNonStaffChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Address
        {
            get
            {
                return StructuralObject.GetValidValue(_address);
            }
            set
            {
                if (!StructuralObject.BinaryEquals(_address, value))
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _address = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }

        private global::System.Byte[] _address;
        partial void OnAddressChanging(global::System.Byte[] value);
        partial void OnAddressChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact
        {
            get
            {
                return _contact;
            }
            set
            {
                if (_contact != value)
                {
                    OnContactChanging(value);
                    ReportPropertyChanging("Contact");
                    _contact = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Contact");
                    OnContactChanged();
                }
            }
        }

        private global::System.String _contact;
        partial void OnContactChanging(global::System.String value);
        partial void OnContactChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactTel
        {
            get
            {
                return _contactTel;
            }
            set
            {
                if (_contactTel != value)
                {
                    OnContactTelChanging(value);
                    ReportPropertyChanging("ContactTel");
                    _contactTel = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("ContactTel");
                    OnContactTelChanged();
                }
            }
        }

        private global::System.String _contactTel;
        partial void OnContactTelChanging(global::System.String value);
        partial void OnContactTelChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _describe;
            }
            set
            {
                if (_describe != value)
                {
                    OnDescribeChanging(value);
                    ReportPropertyChanging("Describe");
                    _describe = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Describe");
                    OnDescribeChanged();
                }
            }
        }

        private global::System.String _describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();

        #endregion
    }
}
#pragma warning restore 1591