#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace classRoomWebSite.Data
{
    [EdmEntityTypeAttribute(NamespaceName="classRoomWebSite.Data", Name="CourseIntro")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class CourseIntro : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new CourseIntro object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static CourseIntro CreateCourseIntro(global::System.Guid identification, global::System.String name)
        {
            CourseIntro courseIntro = new CourseIntro();
            courseIntro.Identification = identification;
            courseIntro.Name = name;

            return courseIntro;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Guid _identification;
        partial void OnIdentificationChanging(global::System.Guid value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }

        private global::System.String _name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _describe;
            }
            set
            {
                if (_describe != value)
                {
                    OnDescribeChanging(value);
                    ReportPropertyChanging("Describe");
                    _describe = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Describe");
                    OnDescribeChanged();
                }
            }
        }

        private global::System.String _describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Pic1
        {
            get
            {
                return StructuralObject.GetValidValue(_pic1);
            }
            set
            {
                if (!StructuralObject.BinaryEquals(_pic1, value))
                {
                    OnPic1Changing(value);
                    ReportPropertyChanging("Pic1");
                    _pic1 = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Pic1");
                    OnPic1Changed();
                }
            }
        }

        private global::System.Byte[] _pic1;
        partial void OnPic1Changing(global::System.Byte[] value);
        partial void OnPic1Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pic2
        {
            get
            {
                return _pic2;
            }
            set
            {
                if (_pic2 != value)
                {
                    OnPic2Changing(value);
                    ReportPropertyChanging("Pic2");
                    _pic2 = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Pic2");
                    OnPic2Changed();
                }
            }
        }

        private global::System.String _pic2;
        partial void OnPic2Changing(global::System.String value);
        partial void OnPic2Changed();

        #endregion
    }
}
#pragma warning restore 1591