#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace classRoomWebSite.Data
{
    [EdmEntityTypeAttribute(NamespaceName="classRoomWebSite.Data", Name="QuestionAnser")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class QuestionAnser : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new QuestionAnser object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        public static QuestionAnser CreateQuestionAnser(global::System.Guid identification)
        {
            QuestionAnser questionAnser = new QuestionAnser();
            questionAnser.Identification = identification;

            return questionAnser;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Guid _identification;
        partial void OnIdentificationChanging(global::System.Guid value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? Cat1
        {
            get
            {
                return _cat1;
            }
            set
            {
                if (_cat1 != value)
                {
                    OnCat1Changing(value);
                    ReportPropertyChanging("Cat1");
                    _cat1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cat1");
                    OnCat1Changed();
                }
            }
        }

        private global::System.Int32? _cat1;
        partial void OnCat1Changing(global::System.Int32? value);
        partial void OnCat1Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? Cat2
        {
            get
            {
                return _cat2;
            }
            set
            {
                if (_cat2 != value)
                {
                    OnCat2Changing(value);
                    ReportPropertyChanging("Cat2");
                    _cat2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cat2");
                    OnCat2Changed();
                }
            }
        }

        private global::System.Int32? _cat2;
        partial void OnCat2Changing(global::System.Int32? value);
        partial void OnCat2Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pic1
        {
            get
            {
                return _pic1;
            }
            set
            {
                if (_pic1 != value)
                {
                    OnPic1Changing(value);
                    ReportPropertyChanging("Pic1");
                    _pic1 = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Pic1");
                    OnPic1Changed();
                }
            }
        }

        private global::System.String _pic1;
        partial void OnPic1Changing(global::System.String value);
        partial void OnPic1Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pic2
        {
            get
            {
                return _pic2;
            }
            set
            {
                if (_pic2 != value)
                {
                    OnPic2Changing(value);
                    ReportPropertyChanging("Pic2");
                    _pic2 = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Pic2");
                    OnPic2Changed();
                }
            }
        }

        private global::System.String _pic2;
        partial void OnPic2Changing(global::System.String value);
        partial void OnPic2Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _describe;
            }
            set
            {
                if (_describe != value)
                {
                    OnDescribeChanging(value);
                    ReportPropertyChanging("Describe");
                    _describe = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Describe");
                    OnDescribeChanged();
                }
            }
        }

        private global::System.String _describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();

        #endregion
    }
}
#pragma warning restore 1591