#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace classRoomWebSite.Data
{
    [EdmEntityTypeAttribute(NamespaceName="classRoomWebSite.Data", Name="Student")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class Student : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Student CreateStudent(global::System.Guid identification, global::System.String name)
        {
            Student student = new Student();
            student.Identification = identification;
            student.Name = name;

            return student;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Guid _identification;
        partial void OnIdentificationChanging(global::System.Guid value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }

        private global::System.String _name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? BirthDay
        {
            get
            {
                return _birthDay;
            }
            set
            {
                if (_birthDay != value)
                {
                    OnBirthDayChanging(value);
                    ReportPropertyChanging("BirthDay");
                    _birthDay = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BirthDay");
                    OnBirthDayChanged();
                }
            }
        }

        private global::System.DateTime? _birthDay;
        partial void OnBirthDayChanging(global::System.DateTime? value);
        partial void OnBirthDayChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _gender;
            }
            set
            {
                if (_gender != value)
                {
                    OnGenderChanging(value);
                    ReportPropertyChanging("Gender");
                    _gender = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Gender");
                    OnGenderChanged();
                }
            }
        }

        private global::System.String _gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? CreateDate
        {
            get
            {
                return _createDate;
            }
            set
            {
                if (_createDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _createDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }

        private global::System.DateTime? _createDate;
        partial void OnCreateDateChanging(global::System.DateTime? value);
        partial void OnCreateDateChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Education
        {
            get
            {
                return _education;
            }
            set
            {
                if (_education != value)
                {
                    OnEducationChanging(value);
                    ReportPropertyChanging("Education");
                    _education = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Education");
                    OnEducationChanged();
                }
            }
        }

        private global::System.String _education;
        partial void OnEducationChanging(global::System.String value);
        partial void OnEducationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _address;
            }
            set
            {
                if (_address != value)
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _address = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }

        private global::System.String _address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _company;
            }
            set
            {
                if (_company != value)
                {
                    OnCompanyChanging(value);
                    ReportPropertyChanging("Company");
                    _company = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Company");
                    OnCompanyChanged();
                }
            }
        }

        private global::System.String _company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telno
        {
            get
            {
                return _telno;
            }
            set
            {
                if (_telno != value)
                {
                    OnTelnoChanging(value);
                    ReportPropertyChanging("Telno");
                    _telno = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Telno");
                    OnTelnoChanged();
                }
            }
        }

        private global::System.String _telno;
        partial void OnTelnoChanging(global::System.String value);
        partial void OnTelnoChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cellno
        {
            get
            {
                return _cellno;
            }
            set
            {
                if (_cellno != value)
                {
                    OnCellnoChanging(value);
                    ReportPropertyChanging("Cellno");
                    _cellno = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Cellno");
                    OnCellnoChanged();
                }
            }
        }

        private global::System.String _cellno;
        partial void OnCellnoChanging(global::System.String value);
        partial void OnCellnoChanged();

        #endregion
    }
}
#pragma warning restore 1591