#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace classRoomWebSite.Data
{
    [EdmEntityTypeAttribute(NamespaceName="classRoomWebSite.Data", Name="TaiwanZipCode")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class TaiwanZipCode : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new TaiwanZipCode object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        /// <param name="cityName">Initial value of the CityName property.</param>
        /// <param name="town">Initial value of the Town property.</param>
        /// <param name="sequence">Initial value of the Sequence property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static TaiwanZipCode CreateTaiwanZipCode(global::System.Int32 identification, global::System.Int32 zip, global::System.String cityName, global::System.String town, global::System.Int32 sequence, global::System.DateTime createDate)
        {
            TaiwanZipCode taiwanZipCode = new TaiwanZipCode();
            taiwanZipCode.Identification = identification;
            taiwanZipCode.Zip = zip;
            taiwanZipCode.CityName = cityName;
            taiwanZipCode.Town = town;
            taiwanZipCode.Sequence = sequence;
            taiwanZipCode.CreateDate = createDate;

            return taiwanZipCode;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Int32 _identification;
        partial void OnIdentificationChanging(global::System.Int32 value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Zip
        {
            get
            {
                return _zip;
            }
            set
            {
                if (_zip != value)
                {
                    OnZipChanging(value);
                    ReportPropertyChanging("Zip");
                    _zip = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Zip");
                    OnZipChanged();
                }
            }
        }

        private global::System.Int32 _zip;
        partial void OnZipChanging(global::System.Int32 value);
        partial void OnZipChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _cityName;
            }
            set
            {
                if (_cityName != value)
                {
                    OnCityNameChanging(value);
                    ReportPropertyChanging("CityName");
                    _cityName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CityName");
                    OnCityNameChanged();
                }
            }
        }

        private global::System.String _cityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Town
        {
            get
            {
                return _town;
            }
            set
            {
                if (_town != value)
                {
                    OnTownChanging(value);
                    ReportPropertyChanging("Town");
                    _town = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Town");
                    OnTownChanged();
                }
            }
        }

        private global::System.String _town;
        partial void OnTownChanging(global::System.String value);
        partial void OnTownChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sequence
        {
            get
            {
                return _sequence;
            }
            set
            {
                if (_sequence != value)
                {
                    OnSequenceChanging(value);
                    ReportPropertyChanging("Sequence");
                    _sequence = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Sequence");
                    OnSequenceChanged();
                }
            }
        }

        private global::System.Int32 _sequence;
        partial void OnSequenceChanging(global::System.Int32 value);
        partial void OnSequenceChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _createDate;
            }
            set
            {
                if (_createDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _createDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }

        private global::System.DateTime _createDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion
    }
}
#pragma warning restore 1591