#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace classRoomWebSite.Data
{
    [EdmEntityTypeAttribute(NamespaceName="classRoomWebSite.Data", Name="Teacher")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class Teacher : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new Teacher object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static Teacher CreateTeacher(global::System.Guid identification, global::System.String name, global::System.DateTime createDate)
        {
            Teacher teacher = new Teacher();
            teacher.Identification = identification;
            teacher.Name = name;
            teacher.CreateDate = createDate;

            return teacher;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Guid _identification;
        partial void OnIdentificationChanging(global::System.Guid value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PicFile
        {
            get
            {
                return _picFile;
            }
            set
            {
                if (_picFile != value)
                {
                    OnPicFileChanging(value);
                    ReportPropertyChanging("PicFile");
                    _picFile = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("PicFile");
                    OnPicFileChanged();
                }
            }
        }

        private global::System.String _picFile;
        partial void OnPicFileChanging(global::System.String value);
        partial void OnPicFileChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }

        private global::System.String _name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _gender;
            }
            set
            {
                if (_gender != value)
                {
                    OnGenderChanging(value);
                    ReportPropertyChanging("Gender");
                    _gender = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Gender");
                    OnGenderChanged();
                }
            }
        }

        private global::System.String _gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _createDate;
            }
            set
            {
                if (_createDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _createDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }

        private global::System.DateTime _createDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? BirthDay
        {
            get
            {
                return _birthDay;
            }
            set
            {
                if (_birthDay != value)
                {
                    OnBirthDayChanging(value);
                    ReportPropertyChanging("BirthDay");
                    _birthDay = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BirthDay");
                    OnBirthDayChanged();
                }
            }
        }

        private global::System.DateTime? _birthDay;
        partial void OnBirthDayChanging(global::System.DateTime? value);
        partial void OnBirthDayChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _address;
            }
            set
            {
                if (_address != value)
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _address = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }

        private global::System.String _address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OfficeAddress
        {
            get
            {
                return _officeAddress;
            }
            set
            {
                if (_officeAddress != value)
                {
                    OnOfficeAddressChanging(value);
                    ReportPropertyChanging("OfficeAddress");
                    _officeAddress = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("OfficeAddress");
                    OnOfficeAddressChanged();
                }
            }
        }

        private global::System.String _officeAddress;
        partial void OnOfficeAddressChanging(global::System.String value);
        partial void OnOfficeAddressChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelPhone
        {
            get
            {
                return _telPhone;
            }
            set
            {
                if (_telPhone != value)
                {
                    OnTelPhoneChanging(value);
                    ReportPropertyChanging("TelPhone");
                    _telPhone = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("TelPhone");
                    OnTelPhoneChanged();
                }
            }
        }

        private global::System.String _telPhone;
        partial void OnTelPhoneChanging(global::System.String value);
        partial void OnTelPhoneChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellPhone
        {
            get
            {
                return _cellPhone;
            }
            set
            {
                if (_cellPhone != value)
                {
                    OnCellPhoneChanging(value);
                    ReportPropertyChanging("CellPhone");
                    _cellPhone = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("CellPhone");
                    OnCellPhoneChanged();
                }
            }
        }

        private global::System.String _cellPhone;
        partial void OnCellPhoneChanging(global::System.String value);
        partial void OnCellPhoneChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Job
        {
            get
            {
                return _job;
            }
            set
            {
                if (_job != value)
                {
                    OnJobChanging(value);
                    ReportPropertyChanging("Job");
                    _job = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Job");
                    OnJobChanged();
                }
            }
        }

        private global::System.String _job;
        partial void OnJobChanging(global::System.String value);
        partial void OnJobChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ability
        {
            get
            {
                return _ability;
            }
            set
            {
                if (_ability != value)
                {
                    OnAbilityChanging(value);
                    ReportPropertyChanging("Ability");
                    _ability = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Ability");
                    OnAbilityChanged();
                }
            }
        }

        private global::System.String _ability;
        partial void OnAbilityChanging(global::System.String value);
        partial void OnAbilityChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Educational
        {
            get
            {
                return _educational;
            }
            set
            {
                if (_educational != value)
                {
                    OnEducationalChanging(value);
                    ReportPropertyChanging("Educational");
                    _educational = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Educational");
                    OnEducationalChanged();
                }
            }
        }

        private global::System.String _educational;
        partial void OnEducationalChanging(global::System.String value);
        partial void OnEducationalChanged();

        #endregion
    }
}
#pragma warning restore 1591