//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("CodeSmith Tools, LLC")]
[assembly: AssemblyProduct("PLINQO for Entity Framework")]
[assembly: AssemblyCopyright("Copyright (c) 2002-2014 CodeSmith Tools, LLC.  All rights reserved.")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.3.0.3047")]
[assembly: AssemblyInformationalVersion("1.3.0.3047")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "CodeSmith Tools, LLC";
    
    internal const string AssemblyProduct = "PLINQO for Entity Framework";
    
    internal const string AssemblyCopyright = "Copyright (c) 2002-2014 CodeSmith Tools, LLC.  All rights reserved.";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.3.0.3047";
    
    internal const string AssemblyInformationalVersion = "1.3.0.3047";
    
    private ThisAssembly() {
    }
}
