#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web.Mvc;

namespace classRoomWebSite.Data.Controllers
{
    public partial class AdminController : Controller
    {
        public ActionResult Index()
        {
            return View("CalendarDetails");
        }

        public ActionResult CalendarDetails()
        {
            return View();
        }

        public ActionResult Cat1s()
        {
            return View();
        }

        public ActionResult Cat2s()
        {
            return View();
        }

        public ActionResult CourseIntros()
        {
            return View();
        }

        public ActionResult QuestionAnsers()
        {
            return View();
        }

        public ActionResult Students()
        {
            return View();
        }

        public ActionResult SystemUsers()
        {
            return View();
        }

        public ActionResult TaiwanZipCodes()
        {
            return View();
        }

        public ActionResult Teachers()
        {
            return View();
        }
    }
}