#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;
using classRoomWebSite.Data;

namespace classRoomWebSite.Data.Controllers.API
{
    [CodeSmith.Data.Web.Http.PagingAndFiltering]
    public partial class CourseIntroController : ApiController
    {
        private classRoomWebSite.Data.classRoomWebSiteDataContext _context = new classRoomWebSite.Data.classRoomWebSiteDataContext();

        #region Get

        public classRoomWebSite.Data.CourseIntro GetByKey(System.Guid identification)
        {
            var courseIntro = _context.CourseIntro.GetByKey(identification);
            if (courseIntro == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            return courseIntro;
        }

        public IQueryable<classRoomWebSite.Data.CourseIntro> GetAll()
        {
            return _context.CourseIntro.AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.CourseIntro> GetByName(System.String name)
        {
            return _context.CourseIntro.ByName(name).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.CourseIntro> GetByDescribe(System.String describe)
        {
            return _context.CourseIntro.ByDescribe(describe).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.CourseIntro> GetByPic2(System.String pic2)
        {
            return _context.CourseIntro.ByPic2(pic2).AsQueryable();
        }

        #endregion

        public HttpResponseMessage Post(classRoomWebSite.Data.CourseIntro value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            _context.CourseIntro.AddObject(value);
            _context.SaveChanges();

            var response = Request.CreateResponse<classRoomWebSite.Data.CourseIntro>(HttpStatusCode.Created, value);
            response.Headers.Location = new Uri( Url.Link("DefaultApi", new { Identification = value.Identification }));

            return response;
        }

        public HttpResponseMessage Put(classRoomWebSite.Data.CourseIntro value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            var courseIntro = _context.CourseIntro.GetByKey(value.Identification);
            if (courseIntro == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            _context.ApplyCurrentValues(courseIntro.EntityKey.EntitySetName, value);
            _context.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Delete(System.Guid identification)
        {
            var courseIntro = _context.CourseIntro.GetByKey(identification);
            if (courseIntro == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            _context.CourseIntro.DeleteObject(courseIntro);
            _context.SaveChanges();
            
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}
