#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;
using classRoomWebSite.Data;

namespace classRoomWebSite.Data.Controllers.API
{
    [CodeSmith.Data.Web.Http.PagingAndFiltering]
    public partial class StudentController : ApiController
    {
        private classRoomWebSite.Data.classRoomWebSiteDataContext _context = new classRoomWebSite.Data.classRoomWebSiteDataContext();

        #region Get

        public classRoomWebSite.Data.Student GetByKey(System.Guid identification)
        {
            var student = _context.Student.GetByKey(identification);
            if (student == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            return student;
        }

        public IQueryable<classRoomWebSite.Data.Student> GetAll()
        {
            return _context.Student.AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByName(System.String name)
        {
            return _context.Student.ByName(name).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByBirthDay(System.DateTime? birthDay)
        {
            return _context.Student.ByBirthDay(birthDay).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByGender(System.String gender)
        {
            return _context.Student.ByGender(gender).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByCreateDate(System.DateTime? createDate)
        {
            return _context.Student.ByCreateDate(createDate).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByEducation(System.String education)
        {
            return _context.Student.ByEducation(education).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByAddress(System.String address)
        {
            return _context.Student.ByAddress(address).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByCompany(System.String company)
        {
            return _context.Student.ByCompany(company).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByTelno(System.String telno)
        {
            return _context.Student.ByTelno(telno).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Student> GetByCellno(System.String cellno)
        {
            return _context.Student.ByCellno(cellno).AsQueryable();
        }

        #endregion

        public HttpResponseMessage Post(classRoomWebSite.Data.Student value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            _context.Student.AddObject(value);
            _context.SaveChanges();

            var response = Request.CreateResponse<classRoomWebSite.Data.Student>(HttpStatusCode.Created, value);
            response.Headers.Location = new Uri( Url.Link("DefaultApi", new { Identification = value.Identification }));

            return response;
        }

        public HttpResponseMessage Put(classRoomWebSite.Data.Student value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            var student = _context.Student.GetByKey(value.Identification);
            if (student == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            _context.ApplyCurrentValues(student.EntityKey.EntitySetName, value);
            _context.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Delete(System.Guid identification)
        {
            var student = _context.Student.GetByKey(identification);
            if (student == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            _context.Student.DeleteObject(student);
            _context.SaveChanges();
            
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}
