#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;
using classRoomWebSite.Data;

namespace classRoomWebSite.Data.Controllers.API
{
    [CodeSmith.Data.Web.Http.PagingAndFiltering]
    public partial class SystemUserController : ApiController
    {
        private classRoomWebSite.Data.classRoomWebSiteDataContext _context = new classRoomWebSite.Data.classRoomWebSiteDataContext();

        #region Get

        public classRoomWebSite.Data.SystemUser GetByKey(System.Guid identification)
        {
            var systemUser = _context.SystemUser.GetByKey(identification);
            if (systemUser == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            return systemUser;
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetAll()
        {
            return _context.SystemUser.AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetByName(System.String name)
        {
            return _context.SystemUser.ByName(name).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetByAccount(System.String account)
        {
            return _context.SystemUser.ByAccount(account).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetByPassword(System.String password)
        {
            return _context.SystemUser.ByPassword(password).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetBySalt(System.String salt)
        {
            return _context.SystemUser.BySalt(salt).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetByEmail(System.String email)
        {
            return _context.SystemUser.ByEmail(email).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetByCreateDate(System.DateTime createDate)
        {
            return _context.SystemUser.ByCreateDate(createDate).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.SystemUser> GetByUpdateDate(System.DateTime updateDate)
        {
            return _context.SystemUser.ByUpdateDate(updateDate).AsQueryable();
        }

        #endregion

        public HttpResponseMessage Post(classRoomWebSite.Data.SystemUser value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            _context.SystemUser.AddObject(value);
            _context.SaveChanges();

            var response = Request.CreateResponse<classRoomWebSite.Data.SystemUser>(HttpStatusCode.Created, value);
            response.Headers.Location = new Uri( Url.Link("DefaultApi", new { Identification = value.Identification }));

            return response;
        }

        public HttpResponseMessage Put(classRoomWebSite.Data.SystemUser value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            var systemUser = _context.SystemUser.GetByKey(value.Identification);
            if (systemUser == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            _context.ApplyCurrentValues(systemUser.EntityKey.EntitySetName, value);
            _context.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Delete(System.Guid identification)
        {
            var systemUser = _context.SystemUser.GetByKey(identification);
            if (systemUser == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            _context.SystemUser.DeleteObject(systemUser);
            _context.SaveChanges();
            
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}
