#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;
using classRoomWebSite.Data;

namespace classRoomWebSite.Data.Controllers.API
{
    [CodeSmith.Data.Web.Http.PagingAndFiltering]
    public partial class TeacherController : ApiController
    {
        private classRoomWebSite.Data.classRoomWebSiteDataContext _context = new classRoomWebSite.Data.classRoomWebSiteDataContext();

        #region Get

        public classRoomWebSite.Data.Teacher GetByKey(System.Guid identification)
        {
            var teacher = _context.Teacher.GetByKey(identification);
            if (teacher == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            return teacher;
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetAll()
        {
            return _context.Teacher.AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByPicFile(System.String picFile)
        {
            return _context.Teacher.ByPicFile(picFile).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByName(System.String name)
        {
            return _context.Teacher.ByName(name).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByGender(System.String gender)
        {
            return _context.Teacher.ByGender(gender).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByCreateDate(System.DateTime createDate)
        {
            return _context.Teacher.ByCreateDate(createDate).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByBirthDay(System.DateTime? birthDay)
        {
            return _context.Teacher.ByBirthDay(birthDay).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByAddress(System.String address)
        {
            return _context.Teacher.ByAddress(address).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByOfficeAddress(System.String officeAddress)
        {
            return _context.Teacher.ByOfficeAddress(officeAddress).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByTelPhone(System.String telPhone)
        {
            return _context.Teacher.ByTelPhone(telPhone).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByCellPhone(System.String cellPhone)
        {
            return _context.Teacher.ByCellPhone(cellPhone).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByJob(System.String job)
        {
            return _context.Teacher.ByJob(job).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByAbility(System.String ability)
        {
            return _context.Teacher.ByAbility(ability).AsQueryable();
        }

        public IQueryable<classRoomWebSite.Data.Teacher> GetByEducational(System.String educational)
        {
            return _context.Teacher.ByEducational(educational).AsQueryable();
        }

        #endregion

        public HttpResponseMessage Post(classRoomWebSite.Data.Teacher value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            _context.Teacher.AddObject(value);
            _context.SaveChanges();

            var response = Request.CreateResponse<classRoomWebSite.Data.Teacher>(HttpStatusCode.Created, value);
            response.Headers.Location = new Uri( Url.Link("DefaultApi", new { Identification = value.Identification }));

            return response;
        }

        public HttpResponseMessage Put(classRoomWebSite.Data.Teacher value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            var teacher = _context.Teacher.GetByKey(value.Identification);
            if (teacher == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            _context.ApplyCurrentValues(teacher.EntityKey.EntitySetName, value);
            _context.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Delete(System.Guid identification)
        {
            var teacher = _context.Teacher.GetByKey(identification);
            if (teacher == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            _context.Teacher.DeleteObject(teacher);
            _context.SaveChanges();
            
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}
